# openapi2-functions.yaml
swagger: '2.0'
info:
  title: reminders-api 
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:

  /:user/reminder:
    post:
      summary: Create a reminder
      operationId: create-reminder
      x-google-backend:
        address: https://GCP_REGION-set-reminders.cloudfunctions.net/reminderCreate
      responses:
        '201':
          description: A reminder was created successfully  
          schema:
            type: '#/definitions/Reminder'
        
  /:user/reminder:
    get:
      summary: Get all reminders
      operationId: get-all-reminders
      x-google-backend:
        address: https://GCP_REGION-set-reminders.cloudfunctions.net/remindersGET
      responses:
        '200':
          description: Reminders were retrieved successfully
          schema:
            type: array
            items: 
               $ref: '#/definitions/Reminder'

  /:user/reminder/:id:
    put:
      summary: Edit a reminder
      operationId: edit-reminder
      x-google-backend:
        address: https://GCP_REGION-set-reminders.cloudfunctions.net/reminderEDIT
      responses:
        '204':
          description: A reminder was edited successfully

  /:user/reminder/:id:
    delete:
      summary: Delete a reminder
      operationId: delete-reminder
      x-google-backend:
        address: https://GCP_REGION-set-reminders.cloudfunctions.net/reminderDELETE
      responses:
        '204':
          description: A reminder was deleted successfully        

definitions:
  Reminder:
    type: object
    required:
     - user
     - description
     - date
     - platforms
    properties:
      user:
        type: string
      description:
        type: string
      date:
        type: date-time
      platforms:
        type: array
        items:
          type: string
