# openapi2-functions.yaml
swagger: '2.0'
info:
  title: reminders-api 
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /:user/reminder:
    get:
      summary: Get all reminders
      operationId: get-all-reminders
      x-google-backend:
        address: https://GCP_REGION-set-reminders.cloudfunctions.net/remindersGET
      responses:
        '200':
          description: A successful response
          schema:
            type: array
            items: 
               $ref: '#/definitions/Reminder'




definitions:
  Reminder:
    type: object
    required:
     - user
     - description
     - date
     - platforms
    properties:
      user:
        type: string
      description:
        type: string
      date:
        type: date-time
      platforms:
        type: array
        items:
          type: string
